version: '3'
services:
  db:
    image: mysql
    container_name: b2bbtask_mysql
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mymysqlrootpassword
      MYSQL_DATABASE: b2bbtask
      MYSQL_USER: b2bbtast_user
      MYSQL_PASSWORD: b2bbtast_password
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysql", "-h", "localhost", "-u", "root", "-pmymysqlrootpassword", "-e", "SELECT 1"]
      timeout: 20s
      retries: 10
  
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: b2bbtask
    command: sh -c "python3 manage.py migrate --noinput && python3 manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      DB_NAME: b2bbtask
      DB_USER: b2bbtast_user
      DB_PASSWORD: b2bbtast_password
      DB_HOST: b2bbtask_mysql
    depends_on:
      - db:
          condition: service_healthy
volumes:
  db_data:
